[package]
name = "macro_sample"
version = "0.1.0"
authors = ["J Burnside <jcburnside97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macro_export = { path = "../macro_export" }